DELETE https://api.test.datacite.org/dois/10.21373/1556894510891
Accept: application/vnd.api+json
Cache-Control: no-cache
# Base64 encoded USERNAME:PASSWORD
Authorization: Basic <>

###

GET https://api.test.datacite.org/dois
Accept: application/vnd.api+json
Cache-Control: no-cache

###

GET https://api.test.datacite.org/dois/10.21373/1557007231832
# Base64 encoded USERNAME:PASSWORD
Authorization: Basic <>
Cache-Control: no-cache

###

POST https://api.test.datacite.org/dois
Content-Type: application/vnd.api+json
# Base64 encoded USERNAME:PASSWORD
Authorization: Basic <>
Cache-Control: no-cache

< doi_model_with_xml_metadata.json

###

PUT https://api.test.datacite.org/dois/10.21373/1556893215451
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json
# Base64 encoded USERNAME:PASSWORD
Authorization: Basic <>
Cache-Control: no-cache

< doi_model_all_nulls.json

###